name: WorldAccessBlocker
version: '${project.version}'
main: net.denfry.worldAccessBlocker.WorldAccessBlocker
api-version: '1.16'
load: STARTUP
authors: [ denfry ]
description: Plugin that blocks access to end, nether, elytra with enhanced features
folia-supported: true

commands:
  wabreload:
    description: "Reload the plugin configuration"
    permission: wab.reload
  wab:
    description: "Manage WorldAccessBlocker restrictions"
    permission: wab.bypass
permissions:
  wab.reload:
    description: "Allows reloading the config"
    default: op
  wab.bypass:
    description: "Allows bypassing restrictions"
    default: op
